### ISSUE TITLE
The crawler should store meta data

### ISSUE THREAD

**Issue by MichaelRoeder** [AKSW/ldspider#34]
The system should offer a central storage containing the metadata that has been collected during the crawling. This meta data might contain (but is not limited to):
* timestamp at which the crawling has been finished
* status of the crawling (maybe we need the information whether the crawling was successful?)
* dcat like information, e.g., that a crawled dump contains the same information as a certain SPARQL endpoint (that does not have to be crawled anymore)
* name of the dump file that has been created

please add additional meta data if needed...

**Comment by MichaelRoeder** [comment]
Looks like we will need a store for this, don't we?

**Comment by earthquakesan** [comment]
Michael, triple store? -)

**Comment by MichaelRoeder** [comment]
Following "eat your own dog food" it would be the best solution. However, I would like to implement the frontier in a way that it can work directly on this store, e.i., throws a lot of queries against it to make sure whether a given URI has not been crawled before. Thus, it has to be
* fast
* able to perform read and write queries at the same time (not exactly at the same time, but you know what I mean ;-) )
