### ISSUE TITLE
0008: Worker: check robots.txt for the domain

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/ldspider#42]
Worker should request the robots.txt file from the domain and check if it is allowed to crawl it. In case, when crawling is not allowed, drop the whole job package and marked it as crawled.

**Comment by MichaelRoeder** [comment]
referenced by commit bb9c469ef0c9a8c0a35ce8d8957440fe0a6317c6

**Comment by MichaelRoeder** [comment]
The crawler-commons SNAPSHOT version used by us can be found here: https://github.com/MichaelRoeder/crawler-commons

**Comment by MichaelRoeder** [comment]
Some robot.txt files contain extremely large delays. The crawler should define a maximum delay that will be used.
